sale/urls.py
from django.urls import re_path, path

from sale import views

urlpatterns = [
    re_path(r'^index$', views.sale_index, name="sale_index"),
    re_path(r'^data/customer/all$', views.get_data_customer_all, name="data_customer_all"),
    re_path(r'^data/customer/day$', views.get_data_customer_day, name="data_customer_day"),
    re_path(r'^data/money/all$', views.get_data_money_all, name="data_money_all"),
    re_path(r'^data/money/day$', views.get_data_money_day, name="data_money_day"),

    # re_path(r'^goal/regionals/year/api$', views.goal_regionals_year_api, name="goal_regionals_year_api"),
    re_path(r'^goal/regionals/month/api$', views.goal_regionals_month_api, name="goal_regionals_month_api"),

    re_path(r'^payment/company/months/api$', views.payment_company_months_api, name="payment_company_months_api"),
    re_path(r'^payment/company/days/api$', views.payment_company_days_api, name="payment_company_days_api"),

    re_path(r'^saler/list$', views.saler_list, name="saler_list"),
    re_path(r'^saler/list/api$', views.saler_list_api, name="saler_list_api"),
    re_path(r'^saler/info/list/api$', views.saler_info_list_api, name="saler_info_list_api"),
    
    re_path(r'^saler/list/export$', views.export_saler_list, name="export_saler_list"),

    re_path(r'^payment/plan/list$', views.payment_plan_list, name="payment_plan_list"),
    re_path(r'^payment/plan/list/api$', views.payment_plan_list_api, name="payment_plan_list_api"),
    # re_path(r'^payment/plan/list/export$', views.export_payment_plan_list, name="export_payment_plan_list"),

    re_path(r'^portrait/saler$', views.saler_portrait, name="saler_portrait"),
    re_path(r'^portrait/saler/1$', views.saler_portrait1, name="saler_portrait1"),
    re_path(r'^portrait/saler/2$', views.saler_portrait2, name="saler_portrait2"),
    re_path(r'^portrait/saler/3$', views.saler_portrait3, name="saler_portrait3"),
    re_path(r'^data/work/daily$', views.get_data_work_daily, name="data_work_daily"),

    re_path(r'^portrait/fuzzy$', views.fuzzy_portrait, name="fuzzy_portrait"),
    re_path(r'^portrait/region$', views.region_portrait, name="region_portrait"),
    re_path(r'^portrait/department$', views.department_portrait, name="department_portrait"),

    re_path(r'^analysis$', views.opp_analysis, name="opp_analysis"),
    re_path(r'^analysis/tableapi$', views.get_opptable_info, name="opp_tableapi"),
    re_path(r'^analysis/allapi$', views.get_opp_info, name="opp_allapi"),
    re_path(r'^analysis/api$', views.get_oppt_info_single, name="opp_api"),

    re_path(r'^dingding/government/center$', views.dingding_government_center, name="dingding_government_center"),
    re_path(r'^dingding/government/center/tab$', views.dingding_government_center_tab, name="dingding_government_center_tab"),
    re_path(r'^dingding/government/center/table$', views.dingding_government_center_table, name="dingding_government_center_table"),

    re_path(r'^dingding/department/frame/api$', views.dingding_department_frame_api, name="dingding_department_frame_api"),
    re_path(r'^dingding/region/frame/members/api$', views.dingding_region_frame_members_api, name="dingding_region_frame_members_api"),
    re_path(r'^dingding/department/frame/members/api$', views.dingding_department_frame_members_api, name="dingding_department_frame_members_api"),

    re_path(r'^customer/count/sale/center/api$', views.customer_count_sale_center_api, name="customer_count_sale_center_api"),
    re_path(r'^customer/count/region/api$', views.customer_count_region_api, name="customer_count_region_api"),
    re_path(r'^customer/count/department/api$', views.customer_count_department_api, name="customer_count_department_api"),
    re_path(r'^customer/count/saler/api$', views.customer_count_saler_api, name="customer_count_saler_api"),
    re_path(r'^work/daily/department/api$', views.work_daily_department_api, name="work_daily_department_api"),
    re_path(r'^work/daily/department/salers/api$', views.work_daily_department_salers_api, name="work_daily_department_salers_api"),
    re_path(r'^payment/department/days/api$', views.payment_department_days_api, name="payment_department_days_api"),
    re_path(r'^goal/regions/month/api$', views.goal_regions_month_api, name="goal_regions_month_api"),
    re_path(r'^goal/departments/month/api$', views.goal_departments_month_api, name="goal_departments_month_api"),
    re_path(r'^goal/salers/month/api$', views.goal_salers_month_api, name="goal_salers_month_api"),
    re_path(r'^account/count/api$', views.account_count_api, name="account_count_api"),
    re_path(r'^products/account/count/api$', views.products_account_count_api, name="products_account_count_api"),
    re_path(r'^opportunity/count/api$', views.opportunity_count_api, name="opportunity_count_api"),

    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^saler/info/api$', views.saler_info_api, name="saler_info_api"),
    re_path(r'^work/daily/saler/api$', views.work_daily_saler_api, name="work_daily_saler_api"),
    re_path(r'^goal/saler/month/api$', views.goal_saler_month_api, name="goal_saler_month_api"),

    re_path(r'^customer/list/api$', views.customer_list_api, name="sale_customer_list_api"),
    re_path(r'^opportunity/list/api$', views.opportunity_list_api, name="sale_opportunity_list_api"),
    re_path(r'^opportunity$', views.opportunity_info_api, name="sale_opportunity_api"),
    re_path(r'^opportunity/info/api$', views.opportunity_info_api, name="sale_opportunity_info_api"),

    re_path(r'^test$', views.test, name="test"),
    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^tenders/info/api$', views.Tenders.as_view(), name="tenders_info_api"),

    re_path(r'^saler/kpi/overview$', views.saler_kpi_overview, name="saler_kpi_overview"),
    re_path(r'^saler/kpi/overview/api$', views.saler_kpi_overview_api, name="saler_kpi_overview_api"),
    re_path(r'^saler/kpi/month$', views.saler_kpi_month, name="saler_kpi_month"),
    re_path(r'^saler/kpi/month/api$', views.saler_kpi_month_api, name="saler_kpi_month_api"),
    re_path(r'^saler/kpi/month/export$', views.export_saler_kpi_month, name="export_saler_kpi_month"),
    re_path(r'^saler/kpi/history$', views.saler_kpi_history, name="saler_kpi_history"),
    re_path(r'^saler/kpi/history/api$', views.saler_kpi_history_api, name="saler_kpi_history_api"),
    re_path(r'^saler/kpi/history/export$', views.export_saler_kpi_history, name="export_saler_kpi_history"),
]

app_name = "sale"

support/urls.py
# from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings
from support import views


urlpatterns = [
    # path('admin/', admin.site.urls),
    # re_path(r'^center/', include('center.urls'), name='center'),

    re_path(r'^', include('user_center.urls'), name='user_center'),
    re_path('^customer/', include('customer.urls', namespace="customer")),
    re_path('^secretary/', include('secretary.urls', namespace="secretary")),
    re_path('^(.+)\.html', views.show_html),
    re_path('^json/403$', views.json_403),
    re_path('^competitor/', include('competitor.urls')),
    re_path('^sale/', include('sale.urls')),
    re_path('^notice/', include('notice.urls')),
    re_path('^statistical/', include('statistical.urls')),
    re_path('^visit/', include('salerVisit.urls')),
    re_path('^work_platform/', include('work_platform.urls')),

    re_path(r'^xman/', include('xman.urls'), name='xman'),
    re_path('^mobile_cloud/', include('mobile_cloud.urls')),
    re_path('^financial_statements/', include('financial_statements.urls')),
    re_path('^user_log/', include('user_log.urls')),
    re_path('^product/', include('product.urls')),
    re_path('^interface/', include('interface.urls')),
]

# This will work if DEBUG is True

urlpatterns += staticfiles_urlpatterns() #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_center/urls.py
from django.urls import re_path, path

# from . import views
from user_center import views
from django.conf import settings

urlpatterns = [
    path(r'',views.index),
    re_path(r'^index$',views.index, name='index'),
    re_path(r'^base$',views.base, name='base'),
    re_path(r'^login$',views.LoginView.as_view(),name='login'),
    re_path(r'^logout$', views.log_out, name="logout"),
    re_path(r'^login/fast$', views.login_from_old_backend, name="login_fast"),
    re_path(r'^jump$', views.jump_to_old_backend, name="jump"),
    re_path(r'^user/log$', views.user_log, name="user_log"),
    re_path(r'^set_code$',views.set_code, name='set_code'), # 设置随机验证码
    re_path(r'^read_code$',views.read_code, name='read_code'), # 读取缓存中随机验证码
    # path('', views.login),
    # re_path(r'^active$', views.search_active_account, name="search_active_account"),
    path('mirror', views.mirror, name="mirror"),
    path('ding_talk/login', views.ding_talk_login, name="ding_talk_login"),
    path('is/logined', views.is_logined, name="is_logined"),

    # 星光资料相关
    path('user_center/material-list', views.material_list, name="material-list"),
    path('user_center/material/list', views.MaterialListView.as_view(), name="material_list"),
    path('user_center/material', views.MaterialView.as_view(), name="material"),
    path('user_center/video', views.video, name="video"),
    re_path('^user_center/video/(?P<code>.+)$', views.video_stream_handler, name="video_stream_handler"),
]

if settings.MODE in ["develop", "beta"]:
    urlpatterns.append(re_path(r'^api/quick/login$', views.quick_login, name="quick_login"))

app_name = "user_center"

templates/lib/footer.html
{% load static %}
<footer class="footer" style="position:fixed;bottom:0;width:100%;height:auto;">
    <div>
    <strong>CopyRight © 2019 北京智慧星光信息技术有限公司</strong> All rights
    reserved.
        <!-- <span style="float: right;">电话：010-****888    京ICP备*******8号</span> -->
    </div>
</footer>

templates/lib/header.html
{% load static %}
<!--右侧部分开始-->
    <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-info " href="#"><i class="fa fa-bars"></i> </a>
                <!-- <form role="search" class="navbar-form-custom" method="post" action="search_results.html">
                    <div class="form-group">
                        <input type="text" placeholder="请输入您需要查找的内容 …" class="form-control" name="top-search" id="top-search">
                    </div>
                </form> -->
                <h3 class="navbar-form-custom" style="padding-left: 10px; padding-top: 15px;">{{ title }}</h3 class="navbar-form-custom">
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <img alt="image" class="img-circle user-avatar" src="{% if request.user.avatar %}{{ request.user.avatar }}{% else %}{% static 'img/a7.jpg' %}{% endif %}"> 
                        <span>{% if request.user.username %}{{ request.user.username }}{% else %}<a href="{% url 'user_center:login' %}">登录</a>{% endif %}</span>
                    </a>
                    <ul class="dropdown-menu" style="padding: 0; left: 0; right: auto;">
                        <!-- <li class="m-t-xs">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <img alt="image" class="img-circle user-avatar-menu" src="{% static 'img/a7.jpg' %}"> <span>设置</span>
                            </a>
                        </li> -->
                        <li class="m-t-xs">
                            <div class="dropdown-messages-box">
                                <a href="javascript:;">
                                    <i class="fa fa-cog"></i><span style="padding-left: 20px;">设置</span>
                                    <!-- <img alt="image" class="img-circle" src="{% static 'img/a7.jpg' %}"> -->
                                </a>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="{% url 'user_center:logout' %}">
                                    <i class="fa fa-power-off"></i><span style="padding-left: 20px;">登出</span>
                                    <!-- <img alt="image" class="img-circle" src="{% static 'img/a4.jpg' %}"> -->
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                            <!-- <img alt="image" class="img-circle user-avatar" src="{% static 'img/restart.jpg' %}"> <span>重启后台</span> -->
                <!-- {% if request.user.is_superuser %}
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-warning"  style="color:gold"></i><span>重启后台</span>
                        </a>
                    </li>
                {% endif %} -->
            </ul>
        </nav>
    </div>
    <!-- <div class="row J_mainContent" id="content-main">
        <iframe id="J_iframe" width="100%" height="100%" src="./index_v1.html" frameborder="0" data-id="index_v1.html" seamless></iframe>
    </div> -->
<!--右侧部分结束-->

templates/lib/siderbar_left - 副本.html
{% load static %}
<!--左侧导航开始-->
<div style="display: none;" id="siderbar-api">{% url 'user_center:siderbar_api' %}</div>
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="nav-close"><i class="fa fa-cogs"></i>
        <!-- <i class="fa fa-times-circle"></i> -->
    </div>
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs" style="font-size:20px;">
                                <!-- <i class="fa fa-area-chart"></i> -->
                                <i class="fa fa-cogs"></i>
                                <strong class="font-bold">星光运营平台</strong>
                                <!-- <small class="navbar-minimalize"><i class="fa fa-bars"></i></small> -->
                            </span>
                        </span> 
                    </a>
                </div>
                <div class="logo-element">运营
                </div>
            </li>
            

            <li>
                <a class="" href="{% url 'user_center:index' %}">
                    <i class="fa fa-home"></i>
                    <span class="nav-label">首页</span>
                </a>
            </li>
            <li>
                <a class="" href="{% url 'user_center:jump' %}">
                    <i class="fa fa-exchange"></i>
                    <!-- <i class="fa fa-link"></i> -->
                    <span class="nav-label">星光管理系统</span>
                </a>
            </li>
            <!-- {% if request.user.username == "丛大侠" %}
            <li class="line dk"></li>
            <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                <span class="ng-scope">分类</span>
            </li>
            <li class="">
                <a href="javascript:;"><i class="fa fa-user"></i> <span class="nav-label">用户中心 </span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="" href="/admin/user_center/usernew/"><i class="fa fa-meh-o"></i>用户管理</a>
                    </li>
                    <li><a class="" href="/admin/user_center/siderbar/"><i class="fa fa-cube"></i>模块管理</a>
                    </li>
                    <li><a class="" href="/admin/auth/permission/"><i class="fa fa-lock"></i>权限管理</a>
                    </li>
                    <li><a class="" href="/admin/auth/group/"><i class="fa fa-group"></i>角色管理</a>
                    </li>
                </ul>
            </li>
            {% endif %} -->

            {% if perms.user_center.view_siderbar_system_manage %}
            <li class="">
                <a href="javascript:;"><i class="fa fa-user"></i> <span class="nav-label">系统管理 </span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    {% if perms.user_center.view_siderbar_system_manage %}
                        <li><a class="" href="/xman/module/tree"><i class="fa fa-cube"></i>模块管理</a>
                        </li>
                    {% endif %}
                    {% if perms.user_center.view_siderbar_permission_manage %}
                        <li><a class="" href="/xman/perm/list"><i class="fa fa-lock"></i>权限管理</a>
                        </li>
                    {% endif %}
                    {% if perms.user_center.view_siderbar_group_manage %}
                        <li><a class="" href="/xman/role/list"><i class="fa fa-group"></i>角色管理</a>
                        </li>
                    {% endif %}
                    {% if perms.user_center.view_siderbar_user_manage %}
                        <li><a class="" href="/xman/user/list"><i class="fa fa-meh-o"></i>用户管理</a>
                        </li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}
            {% if perms.user_center.view_siderbar_customer_manage %}
            <li>
                <a href="javascript:;"><i class="fa fa-user-secret"></i> <span class="nav-label">客户管理 </span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <!-- {/% if perms.customer.view_customer_list %/} -->
                    {% if request.user.username == '丛大侠' %}
                    <li><a class="" href="#">
                        <i class="fa fa-list-ul"></i>客户列表</a>
                    </li>
                    {% endif %}
                    {% if perms.customer.view_customer_list %}
                    <li><a class="" href="#?coverage=1&status=1&xtype=1">
                        <i class="fa fa-list-ul"></i>公宣客户列表</a>
                    </li>
                    {% endif %}
                    {% if perms.customer.view_customer_activity_list %}
                    <li><a class="" href="#">
                        <i class="fa fa-bar-chart-o"></i>活跃度统计</a>
                    </li>
                    {% endif %}
                    <!-- {/% if perms.user_center.view_siderbar_customer_industry_coverage %/} -->
                    {% if request.user.username == '丛大侠' %}
                    <li><a class="" href="#">
                        <i class="fa fa-industry"></i>行业覆盖率</a>
                    </li>
                    {% endif %}
                    {% if perms.user_center.view_siderbar_government_industry_coverage %}
                    <li><a class="" href="#">
                        <i class="fa fa-industry"></i>公宣覆盖率</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}

            {% if perms.user_center.view_siderbar_competitor_manage %}
            <li>
                <a href="javascript:;"><i class="fa fa-flask"></i> <span class="nav-label">竞品管理 </span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">                    
                {% if perms.user_center.view_siderbar_competitor_list %}
                    <li><a class="" href="#">
                        <i class="fa fa-edit"></i>竞品列表</a>
                    </li>
                {% endif %}                   
                {% if perms.user_center.view_siderbar_competitor_crm %}
                    <li><a class="" href="#">
                        <i class="fa fa-desktop"></i>竞品签约客户</a>
                    </li>
                {% endif %}                   
                {% if perms.user_center.view_siderbar_competitor_analysis %}
                        <li><a class="" href="#">
                        <i class="fa fa-table"></i>竞品分析</a>
                        </li>
                {% endif %}
                </ul>
            </li>
            {% endif %}

            {% if perms.user_center.view_siderbar_sale_manage %}
            <li>
                <a href="javascript:;">
                    <i class="fa fa-dollar"></i> 
                    <span class="nav-label">商务管理 </span> 
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">

                    {% if perms.user_center.view_siderbar_government_center %}
                        <li><a class="" href="/sale/dingding/government/center">
                            <i class="fa fa-flag"></i>政务中心</a>
                        </li>
                    {% endif %}

                    {% if request.user.username == "丛大侠"  %}
                        <li><a class="" href="/sale/portrait/region">
                            <i class="fa fa-square"></i>大区画像</a>
                        </li>
                        <li><a class="" href="/sale/portrait/department">
                            <i class="fa fa-empire"></i>部门画像</a>
                        </li>
                        <li><a class="" href="/sale/portrait/saler">
                            <i class="fa fa-joomla"></i>商务画像</a>
                        </li>
                        <li><a class="" href="/sale/saler/list">
                            <i class="fa fa-android"></i>商务列表</a>
                        </li>
                        <li><a class="" href="/sale/payment/plan/list">
                            <i class="fa fa-credit-card"></i>回款计划</a>
                        </li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}
            {% if perms.user_center.can_see_visit %}
{#            {% if request.user.username  in '"武翠霞","王寅","朱铭鑫","丛大侠","牛于斌"' %}#}
            <li>
                <a href="javascript:;"><i class="fa fa-map-marker"></i> <span class="nav-label">签到总览</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    {% if perms.user_center.can_see_china_visit %}
                    <li><a class="" href="#">
                        <i class="fa fa-map"></i>全国签到</a>
                    </li>
                    {% endif %}

                </ul>
            </li>
            {% endif %}
            {% if perms.user_center.view_siderbar_notice_manage %}
            <li>
                <a href="javascript:;"><i class="fa fa-sticky-note"></i> <span class="nav-label">通知管理 </span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                {% if perms.user_center.view_siderbar_notice_list %}
                    <li><a class="" href="/notice/list?notice_type=3">
                        <i class="fa fa-list-ol"></i>消息列表</a>
                    </li>
                {% endif %}
                {% if perms.user_center.view_siderbar_notice_settings %}
                    <li><a class="" href="/notice/settings">
                        <i class="fa fa-cog"></i>消息设置</a>
                    </li>
                {% endif %}
                </ul>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<!--左侧导航结束-->

templates/lib/watermark.html
{% load static %}
  <watermark>
    <div style="width: 100%;height: 100%;background-color: red;" id="watermark">
      <input type="text" id="uname" value="{{ request.user.username }}" hidden>
    </div>
  </watermark>
{% block js_tail %}
<script>
function watermark(settings) {
    //默认设置
    var defaultSettings = {
        watermark_txt: "text",
        watermark_x: 20, //水印起始位置x轴坐标
        watermark_y: 20, //水印起始位置Y轴坐标
        watermark_rows: 20, //水印行数
        watermark_cols: 20, //水印列数
        watermark_x_space: 60, //水印x轴间隔
        watermark_y_space: 40, //水印y轴间隔
        watermark_color: '#aaa', //水印字体颜色
        watermark_alpha: 0.3, //水印透明度
        watermark_fontsize: '15px', //水印字体大小
        watermark_font: '微软雅黑', //水印字体
        watermark_width: 160, //水印宽度
        watermark_height: 80, //水印长度
        watermark_angle: 20 //水印倾斜度数
    };
    if (arguments.length === 1 && typeof arguments[0] === "object") {
        var src = arguments[0] || {};
        for (key in src) {
            if (src[key] && defaultSettings[key] && src[key] === defaultSettings[key]) continue;
            else if (src[key]) defaultSettings[key] = src[key];
        }
    }
    var oTemp = document.createDocumentFragment();
    //获取页面最大宽度
    var page_width = Math.max(document.body.scrollWidth, document.body.clientWidth);
    var cutWidth = page_width * 0.0150;
    var page_width = page_width - cutWidth;
    //获取页面最大高度
    var page_height = Math.max(document.body.scrollHeight, document.body.clientHeight) + 450;
    page_height = Math.max(page_height, window.innerHeight - 30);
    //如果将水印列数设置为0，或水印列数设置过大，超过页面最大宽度，则重新计算水印列数和水印x轴间隔
    if (defaultSettings.watermark_cols == 0 || (parseInt(defaultSettings.watermark_x + defaultSettings.watermark_width * defaultSettings.watermark_cols + defaultSettings.watermark_x_space * (defaultSettings.watermark_cols - 1)) > page_width)) {
        defaultSettings.watermark_cols = parseInt((page_width - defaultSettings.watermark_x + defaultSettings.watermark_x_space) / (defaultSettings.watermark_width + defaultSettings.watermark_x_space));
        defaultSettings.watermark_x_space = parseInt((page_width - defaultSettings.watermark_x - defaultSettings.watermark_width * defaultSettings.watermark_cols) / (defaultSettings.watermark_cols - 1));
    }
    //如果将水印行数设置为0，或水印行数设置过大，超过页面最大长度，则重新计算水印行数和水印y轴间隔
    if (defaultSettings.watermark_rows == 0 || (parseInt(defaultSettings.watermark_y + defaultSettings.watermark_height * defaultSettings.watermark_rows + defaultSettings.watermark_y_space * (defaultSettings.watermark_rows - 1)) > page_height)) {
        defaultSettings.watermark_rows = parseInt((defaultSettings.watermark_y_space + page_height - defaultSettings.watermark_y) / (defaultSettings.watermark_height + defaultSettings.watermark_y_space));
        defaultSettings.watermark_y_space = parseInt(((page_height - defaultSettings.watermark_y) - defaultSettings.watermark_height * defaultSettings.watermark_rows) / (defaultSettings.watermark_rows - 1));
    }
    var x;
    var y;
    for (var i = 0; i < defaultSettings.watermark_rows; i++) {
        y = defaultSettings.watermark_y + (defaultSettings.watermark_y_space + defaultSettings.watermark_height) * i;
        for (var j = 0; j < defaultSettings.watermark_cols; j++) {
            x = defaultSettings.watermark_x + (defaultSettings.watermark_width + defaultSettings.watermark_x_space) * j;
            var mask_div = document.createElement('div');
            mask_div.id = 'mask_div' + i + j;
            mask_div.className = 'mask_div';
            mask_div.appendChild(document.createTextNode(defaultSettings.watermark_txt));
            //设置水印div倾斜显示
            mask_div.style.webkitTransform = "rotate(-" + defaultSettings.watermark_angle + "deg)";
            mask_div.style.MozTransform = "rotate(-" + defaultSettings.watermark_angle + "deg)";
            mask_div.style.msTransform = "rotate(-" + defaultSettings.watermark_angle + "deg)";
            mask_div.style.OTransform = "rotate(-" + defaultSettings.watermark_angle + "deg)";
            mask_div.style.transform = "rotate(-" + defaultSettings.watermark_angle + "deg)";
            mask_div.style.visibility = "";
            mask_div.style.position = "absolute";
            mask_div.style.left = x + 'px';
            mask_div.style.top = y + 'px';
            mask_div.style.overflow = "hidden";
            mask_div.style.zIndex = "999";
            //让水印不遮挡页面的点击事件
            mask_div.style.pointerEvents = 'none';
            mask_div.style.opacity = defaultSettings.watermark_alpha;
            mask_div.style.fontSize = defaultSettings.watermark_fontsize;
            mask_div.style.fontFamily = defaultSettings.watermark_font;
            mask_div.style.color = defaultSettings.watermark_color;
            mask_div.style.textAlign = "center";
            mask_div.style.width = defaultSettings.watermark_width + 'px';
            mask_div.style.height = defaultSettings.watermark_height + 'px';
            mask_div.style.display = "block";
            oTemp.appendChild(mask_div);
        };
    };
    $('#watermark').append(oTemp);
}
var uname = $('#uname').val()
console.log(uname)
watermark({'watermark_txt':uname})
</script>
{% endblock %}