customer/urls.py
from django.urls import re_path, path

from customer import views

urlpatterns = [
    re_path(r'^list$', views.customer_list, name="customer_list"),
    re_path(r'^government/customer/list$', views.government_customer_list, name="government_customer_list"),
    re_path(r'^list/api$', views.customer_list_api, name="customer_list_api"),
    re_path(r'^list_opp$', views.customer_list_add_api, name="customer_list_add_api"),
    re_path(r'^phone$', views.phone, name="phone"),
    re_path(r'^activity$', views.activity, name="activity"),
    re_path(r'^activity/api$', views.activity_api, name="activity_api"),
    re_path(r'^industry/coverage$', views.industry_coverage, name="industry_coverage"),
    re_path(r'^industry/coverage/api$', views.industry_coverage_api, name="industry_coverage_api"),
    re_path(r'^cities/api$', views.cities_api, name="cities_api"),
    re_path(r'^counties/api$', views.counties_api, name="counties_api"),
    re_path(r'^activity/export/file$', views.activity_export_file, name="activity_export_file"),
    re_path(r'^get_wp_account_ajax$', views.get_wp_account_ajax, name="get_wp_account_ajax"),
    
    re_path(r'^government/industry/coverage$', views.government_industry_coverage, name="government_industry_coverage"),
    re_path(r'^government/industry/coverage/api$', views.government_industry_coverage_api, name="government_industry_coverage_api"),
    re_path(r'^government/industry/coverage/map$', views.get_coverage_map, name="government_industry_coverage_map"),
    re_path(r'^government/industry/coverage/map2$', views.get_coverage_map2, name="government_industry_coverage_map2"),
    re_path(r'^sync_crm/api$', views.sync_crm_api, name="sync_crm_api"),    # 同步最新的客户、商机实时信息api
    re_path(r'^get_account/api$', views.get_account_api, name="get_account_api"),   # 获取快速建账号的基础数据api
    re_path(r'^agent/api$', views.agent_api, name="agent_api"),     # 模糊搜索代理商api
    re_path(r'^opp_owner/api$', views.opp_owner_api, name="opp_owner_api"),     # 获取某个客户关联的所有商机负责人的api
    re_path(r'^get_environment/api$', views.get_environment, name="get_environment"),     # 获取当前环境(product、beta、develop)
    re_path(r'^add_account_php/api$', views.add_account_php, name="add_account_php"),     # 调php生成账号接口
    re_path(r'^get_finalaccount/api$', views.get_finalaccount, name="get_finalaccount"),    #展示最终客户列表
    re_path(r'^sync_account_data/api$', views.sync_account_data, name="sync_account_data"), #同步
    re_path(r'^save_questionnalre/api$', views.save_questionnalre, name="save_questionnalre"),  #存入调研表
    re_path(r'^get_questionnalre/api', views.get_questionnalre, name="get_questionnalre"), #获取调研表
    re_path(r'^get_uuid/api$', views.get_uuid, name="get_uuid"),  #获取uuid
    re_path(r'^add_account/api$', views.add_account, name="add_account"),  #python实现添加秘书账号
    re_path(r'^get_crm_Id/api$', views.get_crm_Id, name="get_crm_Id"),     #获取crm id
]

app_name = "customer"

sale/urls.py
from django.urls import re_path, path

from sale import views

urlpatterns = [
    re_path(r'^index$', views.sale_index, name="sale_index"),
    re_path(r'^data/customer/all$', views.get_data_customer_all, name="data_customer_all"),
    re_path(r'^data/customer/day$', views.get_data_customer_day, name="data_customer_day"),
    re_path(r'^data/money/all$', views.get_data_money_all, name="data_money_all"),
    re_path(r'^data/money/day$', views.get_data_money_day, name="data_money_day"),

    # re_path(r'^goal/regionals/year/api$', views.goal_regionals_year_api, name="goal_regionals_year_api"),
    re_path(r'^goal/regionals/month/api$', views.goal_regionals_month_api, name="goal_regionals_month_api"),

    re_path(r'^payment/company/months/api$', views.payment_company_months_api, name="payment_company_months_api"),
    re_path(r'^payment/company/days/api$', views.payment_company_days_api, name="payment_company_days_api"),

    re_path(r'^saler/list$', views.saler_list, name="saler_list"),
    re_path(r'^saler/list/api$', views.saler_list_api, name="saler_list_api"),
    re_path(r'^saler/info/list/api$', views.saler_info_list_api, name="saler_info_list_api"),
    
    re_path(r'^saler/list/export$', views.export_saler_list, name="export_saler_list"),

    re_path(r'^payment/plan/list$', views.payment_plan_list, name="payment_plan_list"),
    re_path(r'^payment/plan/list/api$', views.payment_plan_list_api, name="payment_plan_list_api"),
    # re_path(r'^payment/plan/list/export$', views.export_payment_plan_list, name="export_payment_plan_list"),

    re_path(r'^portrait/saler$', views.saler_portrait, name="saler_portrait"),
    re_path(r'^portrait/saler/1$', views.saler_portrait1, name="saler_portrait1"),
    re_path(r'^portrait/saler/2$', views.saler_portrait2, name="saler_portrait2"),
    re_path(r'^portrait/saler/3$', views.saler_portrait3, name="saler_portrait3"),
    re_path(r'^data/work/daily$', views.get_data_work_daily, name="data_work_daily"),

    re_path(r'^portrait/fuzzy$', views.fuzzy_portrait, name="fuzzy_portrait"),
    re_path(r'^portrait/region$', views.region_portrait, name="region_portrait"),
    re_path(r'^portrait/department$', views.department_portrait, name="department_portrait"),

    re_path(r'^analysis$', views.opp_analysis, name="opp_analysis"),
    re_path(r'^analysis/tableapi$', views.get_opptable_info, name="opp_tableapi"),
    re_path(r'^analysis/allapi$', views.get_opp_info, name="opp_allapi"),
    re_path(r'^analysis/api$', views.get_oppt_info_single, name="opp_api"),

    re_path(r'^dingding/government/center$', views.dingding_government_center, name="dingding_government_center"),
    re_path(r'^dingding/government/center/tab$', views.dingding_government_center_tab, name="dingding_government_center_tab"),
    re_path(r'^dingding/government/center/table$', views.dingding_government_center_table, name="dingding_government_center_table"),

    re_path(r'^dingding/department/frame/api$', views.dingding_department_frame_api, name="dingding_department_frame_api"),
    re_path(r'^dingding/region/frame/members/api$', views.dingding_region_frame_members_api, name="dingding_region_frame_members_api"),
    re_path(r'^dingding/department/frame/members/api$', views.dingding_department_frame_members_api, name="dingding_department_frame_members_api"),

    re_path(r'^customer/count/sale/center/api$', views.customer_count_sale_center_api, name="customer_count_sale_center_api"),
    re_path(r'^customer/count/region/api$', views.customer_count_region_api, name="customer_count_region_api"),
    re_path(r'^customer/count/department/api$', views.customer_count_department_api, name="customer_count_department_api"),
    re_path(r'^customer/count/saler/api$', views.customer_count_saler_api, name="customer_count_saler_api"),
    re_path(r'^work/daily/department/api$', views.work_daily_department_api, name="work_daily_department_api"),
    re_path(r'^work/daily/department/salers/api$', views.work_daily_department_salers_api, name="work_daily_department_salers_api"),
    re_path(r'^payment/department/days/api$', views.payment_department_days_api, name="payment_department_days_api"),
    re_path(r'^goal/regions/month/api$', views.goal_regions_month_api, name="goal_regions_month_api"),
    re_path(r'^goal/departments/month/api$', views.goal_departments_month_api, name="goal_departments_month_api"),
    re_path(r'^goal/salers/month/api$', views.goal_salers_month_api, name="goal_salers_month_api"),
    re_path(r'^account/count/api$', views.account_count_api, name="account_count_api"),
    re_path(r'^products/account/count/api$', views.products_account_count_api, name="products_account_count_api"),
    re_path(r'^opportunity/count/api$', views.opportunity_count_api, name="opportunity_count_api"),

    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^saler/info/api$', views.saler_info_api, name="saler_info_api"),
    re_path(r'^work/daily/saler/api$', views.work_daily_saler_api, name="work_daily_saler_api"),
    re_path(r'^goal/saler/month/api$', views.goal_saler_month_api, name="goal_saler_month_api"),

    re_path(r'^customer/list/api$', views.customer_list_api, name="sale_customer_list_api"),
    re_path(r'^opportunity/list/api$', views.opportunity_list_api, name="sale_opportunity_list_api"),
    re_path(r'^opportunity$', views.opportunity_info_api, name="sale_opportunity_api"),
    re_path(r'^opportunity/info/api$', views.opportunity_info_api, name="sale_opportunity_info_api"),

    re_path(r'^test$', views.test, name="test"),
    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^tenders/info/api$', views.Tenders.as_view(), name="tenders_info_api"),

    re_path(r'^saler/kpi/overview$', views.saler_kpi_overview, name="saler_kpi_overview"),
    re_path(r'^saler/kpi/overview/api$', views.saler_kpi_overview_api, name="saler_kpi_overview_api"),
    re_path(r'^saler/kpi/month$', views.saler_kpi_month, name="saler_kpi_month"),
    re_path(r'^saler/kpi/month/api$', views.saler_kpi_month_api, name="saler_kpi_month_api"),
    re_path(r'^saler/kpi/month/export$', views.export_saler_kpi_month, name="export_saler_kpi_month"),
    re_path(r'^saler/kpi/history$', views.saler_kpi_history, name="saler_kpi_history"),
    re_path(r'^saler/kpi/history/api$', views.saler_kpi_history_api, name="saler_kpi_history_api"),
    re_path(r'^saler/kpi/history/export$', views.export_saler_kpi_history, name="export_saler_kpi_history"),
]

app_name = "sale"

support/urls.py
# from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings
from support import views


urlpatterns = [
    # path('admin/', admin.site.urls),
    # re_path(r'^center/', include('center.urls'), name='center'),

    re_path(r'^', include('user_center.urls'), name='user_center'),
    re_path('^customer/', include('customer.urls', namespace="customer")),
    re_path('^secretary/', include('secretary.urls', namespace="secretary")),
    re_path('^(.+)\.html', views.show_html),
    re_path('^json/403$', views.json_403),
    re_path('^competitor/', include('competitor.urls')),
    re_path('^sale/', include('sale.urls')),
    re_path('^notice/', include('notice.urls')),
    re_path('^statistical/', include('statistical.urls')),
    re_path('^visit/', include('salerVisit.urls')),
    re_path('^work_platform/', include('work_platform.urls')),

    re_path(r'^xman/', include('xman.urls'), name='xman'),
    re_path('^mobile_cloud/', include('mobile_cloud.urls')),
    re_path('^financial_statements/', include('financial_statements.urls')),
    re_path('^user_log/', include('user_log.urls')),
    re_path('^product/', include('product.urls')),
    re_path('^interface/', include('interface.urls')),
]

# This will work if DEBUG is True

urlpatterns += staticfiles_urlpatterns() #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/views/syncapi.py
import json
import logging
import threading
import time
import traceback
from queue import Queue
from urllib.parse import quote

import requests
from django.http import JsonResponse

from customer.models import Account
from customer.service.syncService import syncCrmaccountsalemapping, syncAccount, syncOpportunity, syncCrmsalemapping


logger = logging.getLogger("customer")


#最终客户搜索
def get_finalaccount(request):
    if request.method == "GET":
        result = {"code": 200, "msg": "", "data": None}

        #搜索框key
        key = request.GET.get("key")
        if not key:
            result["code"] = -1
            return JsonResponse(result)
        key = quote(key)

        try:
            token = '4e33e00381c94a9bba251ebb44996c0f'
            url_account = 'http://192.168.16.90:8800/account/api?field_name=name&field_value={}&token={}'.format(key, token)

            r = requests.get(url_account)
            result["data"] = json.loads(r.text)["data"]
        except Exception as e:
            print(e)
            result["code"] = 500
            result["msg"] = "http://192.168.16.90:8800/account/api down"
            result["data"] = []
            return JsonResponse(result)

        if not result["data"]:
            result["code"] = 201
            result["msg"] = "http://192.168.16.90:8800/account/api down"
            result["data"] = []
            return JsonResponse(result)

        for i in result["data"]:
            acount = Account.objects.filter(new_account_id=i["id"]).exists()
            if acount:
                i["status"] = True
            else:
                i["status"] = False

        return JsonResponse(result)



#点击同步
try:
    def sync_account_data_bak(request):
        if request.method == "GET":
            result = {"code":200, "msg": "", "data": None}
            id = request.GET.get("id")
            status = request.GET.get("status")
            control = 0


            q = Queue(maxsize=4)
            account_t = threading.Thread(target=syncAccount, args=(id, status, q))
            opp_t = threading.Thread(target=syncOpportunity, args=(id, status, q))
            casm_t = threading.Thread(target=syncCrmaccountsalemapping, args=(id, q))
            csm_t = threading.Thread(target=syncCrmsalemapping, args=(id, q))

            casm_t.start()
            csm_t.start()
            account_t.start()
            opp_t.start()

            casm_t.join()
            csm_t.join()
            account_t.join()
            opp_t.join()

            while True:
                time.sleep(0.5)
                if q.full():
                    break

            while not q.empty():
                r, m = q.get()
                if not r:
                    control += 1
                    result["msg"] += m



            # 同步account 表
            synca, _ = syncAccount(id, status)

            if not synca:
                control +=1
                result["msg"] += "account sync failed account1;"

            # 同步opportunity表
            l = []
            synco, _ = syncOpportunity(id, status)
            if not synco:
                control += 1
                result["msg"] += "account sync failed Opportunity;"


            # 同步Crmaccountsalemapping
            syncc, _ = syncCrmaccountsalemapping(id)
            if not syncc:
                control += 1
                result["msg"] += "account sync failed Crmaccountsalemapping;"

            #同步Crmsalemapping
            syncs, _ = syncCrmsalemapping(id)
            if not syncs:
                control += 1
                result["msg"] += "account sync failed Crmsalemapping;"

            if not control:
                result["msg"] += "success"

            if control == 4:
                result["code"] = -1
                result["msg"] = "all sync failed"
                return JsonResponse(result)

            if not control:
                result["msg"] = "success"
                return JsonResponse(result)
            result["code"] = 500
            return JsonResponse(result)
except Exception as e:
    print(traceback.print_exc())


#点击同步
def sync_account_data(request):
    if request.method == "GET":
        result = {"code":200, "msg": "", "data": None}
        id = request.GET.get("id")
        status = request.GET.get("status")
        control = 0

        # 同步opportunity表
        synco, _ = syncAccount(id, status)
        if not synco:
            control += 1
            result["msg"] += "account sync failed;"

        # syncOpportunity
        syncc, _ = syncOpportunity(id, status)
        if not syncc:
            control += 1
            result["msg"] += "opportunity sync failed;"

        # 同步Crmaccountsalemapping
        sync, _ = syncCrmaccountsalemapping(id)
        if not syncc:
            control += 1
            result["msg"] += "accountsalemapping sync failed;"

        # 同步Crmsalemapping
        syncs, _ = syncCrmsalemapping(id)
        if not syncs:
            control += 1
            result["msg"] += "salemapping sync failed;"


        if not control:
            result["msg"] = "success"
            return JsonResponse(result)
        result["code"] = 500
        return JsonResponse(result)

templates/customer/coverage-map.html
{% extends 'base.html' %}
{% load i18n static %}

{% block css_tail %}
<link rel="stylesheet" href="{% static 'css/element-ui@2.13.1/lib/theme-chalk/index.css' %}">

{% endblock %}

{% block body %}
<script src="{% static 'js/npm/vue@2.6.11' %}"></script>
<script src="{% static 'js/axios/dist/axios.min.js' %}"></script>
<script src="{% static 'js/element-ui@2.13.1/lib/index.js' %}"></script>
<script src="{% static 'js/plugins/layui/layui.js' %}"></script>
<div style="display: none;">
    <div id="example"></div>
</div>
<div class="row" style="height: 100%;">

    <div class="col-md-12 padding-5">
        <div class="ibox float-e-margins mbt-0" style="height: 800px;">
            <!-- <div class="ibox-title">
                <h5 style="width: 100%; text-align: center;">公宣覆盖率</h5>
                <div class="ibox-tools"></div>
            </div> -->
            <div class="ibox-content wrap" style="width: 100%; height: 92%;">
                <div id="china-map" style="width: 100%; height: 100%;"></div>
            </div>
        </div>
    </div>
    <div class="clearfix" style="display: none;"></div>
</div>

<div id="init-data" style="display: none;">{{ init_data }}</div>
{% endblock %}

{% block js_tail %}

    <!-- <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
    
    <script src="{% static 'js/plugins/jsKnob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script> -->
    <script src="{% static 'js/plugins/echarts/echarts-all.js' %}"></script>
    <script src="{% static 'js/plugins/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'js/plugins/echarts/china.js' %}"></script>
    <script src="{% static 'js/customer/china-map1.js' %}"></script>
{% endblock %}

templates/customer/government_industry_coverage.html
{% extends 'base.html' %}
{% load i18n static %}

{% block css_tail %}
<!-- jqgrid-->
<link href="{% static 'css/plugins/jqgrid/ui.jqgrid.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<script>

</script>
<div style="display: none;">
    <div id="department-data">{{ industry_data }}</div>
    <div id="department-data-1">{{ industry_data_1 }}</div>
    <div id="industry-coverage-api">{% url 'customer:government_industry_coverage_api' %}</div>
    <div id="fields-to-check">{{ fields_to_check }}</div>
    <div id="states">{{ states }}</div>
    <div id="cities">{{ cities }}</div>
    <div id="districts">{{ districts }}</div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div style="margin-top: 10px;"></div>
        <div class="ibox float-e-margins" style="margin-bottom: 10px;">
            <div class="ibox-content">
                <form method="GET" onsubmit="return false;" class="form-horizontal" id="industry-coverage-filter-form">
                    <!-- {% csrf_token %} -->
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="col-lg-2 col-md-3 col-sm-3" style="margin-top: 5px;" id="location-div-1">
                                <label>客户地域-省：</label>
                                <!-- <label><nobr>客户地域：</nobr></label> -->
                                <select type="text" class="form-control" name="state" style="padding-top: 2px;"
                                        id="location-select-1" onchange="onSelectChange('location', 1, commonLocation.getCities)"></select>
                                <!-- {{ form.state }} -->
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-3" style="margin-top: 5px; display: none;" id="location-div-2">
                                <label><nobr>客户地域-市：</nobr></label>
                                <select type="text" class="form-control" name="city" style="padding-top: 2px;"
                                        id="location-select-2" onchange="onSelectChange('location', 2, commonLocation.getDistricts)"></select>
                                <!-- {{ form.city }} -->
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-3" style="margin-top: 5px; display: none;" id="location-div-3">
                                <label><nobr>客户地域-县：</nobr></label>
                                <select type="text" class="form-control" name="district" 
                                style="padding-top: 2px;" id="location-select-3"></select>
                                <!-- {{ form.district }} -->
                            </div>

                            <div class="col-lg-2 col-md-2, col-sm-3" style="margin-top: 5px; display: none;">
                                <input name="industry" id="department-value" />
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" id="id_department-1" style="margin-top: 5px;">
                                <label><nobr>一级行业：</nobr></label>
                                {{ form.industry1 }}
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" id="id_department-2" style="margin-top: 5px">
                                <label><nobr>二级行业:</nobr></label>
                                {{ form.industry2 }}
                            </div>

                            <div class="col-lg-2 col-md-2, col-sm-3" style="float: right; margin-top: 5px;">
                                <label></label>
                                <div>                                        
                                    <button class="btn btn-primary col-md-6" type="submit" id="submitBtn">搜索</button>
                                    <button class="btn btn-white col-md-3" type="reset" style="float: right;" id="resetBtn">重置</button>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
        <div class="ibox ">
            <div class="ibox-content">

                <div class="jqGrid_wrapper">
                    <table id="table_list_1"></table>
                    <div id="pager_list_1"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="init-data" style="display: none;">{{ init_data }}</div>
{% endblock %}

{% block js_tail %}
    <!-- Peity -->
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>

    <!-- jqGrid -->
    <script src="{% static 'js/plugins/jqgrid/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/jquery.jqGrid.min.js' %}"></script>
    <script src="{% static 'js/content.js' %}"></script>
    <script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'js/plugins/jsKnob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'js/customer/government_industry_coverage_list.js' %}"></script>
{% endblock %}

templates/customer/industry_coverage.html
{% extends 'base.html' %}
{% load i18n static %}

{% block css_tail %}
<!-- jqgrid-->
<link href="{% static 'css/plugins/jqgrid/ui.jqgrid.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<script>

</script>
<div style="display: none;">
    <div id="department-data">{{ industry_data }}</div>
    <div id="department-data-1">{{ industry_data_1 }}</div>
    <div id="industry-coverage-api">{% url 'customer:industry_coverage_api' %}</div>
    <div id="fields-to-check">{{ fields_to_check }}</div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div style="margin-top: 10px;"></div>
        <div class="ibox float-e-margins" style="margin-bottom: 10px;">
            <div class="ibox-content">
                <form method="GET" onsubmit="return false;" class="form-horizontal" id="industry-coverage-filter-form">
                    <!-- {% csrf_token %} -->
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="col-lg-2 col-md-2, col-sm-3" style="margin-top: 5px; display: none;">
                                <input name="industry" id="department-value" />
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" id="id_department-1" style="margin-top: 5px;">
                                <label><nobr>一级行业：</nobr></label>
                                <select type="text" class="form-control" id="department-1" name="industry1" onchange="onDepartmentChange1()" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" id="id_department-2" style="margin-top: 5px; display: none;">
                                <label><nobr>二级行业:</nobr></label>
                                <select type="text" class="form-control" id="department-2" name="industry2" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" style="margin-top: 5px;" id="id_province">
                                <!-- <label>客户地域-省：</label> -->
                                <label><nobr>客户地域：</nobr></label>
                                <!-- <select type="text" class="form-control" name="customer_province"></select> -->
                                {{ form.location }}
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" style="margin-top: 5px; display: none;" id="id_city">
                                <label><nobr>客户地域-市：</nobr></label>
                                <!-- <select type="text" class="form-control" name="customer_city"></select> -->
                                {{ form.customer_city }}
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" style="margin-top: 5px; display: none;" id="id_county">
                                <label><nobr>客户地域-县：</nobr></label>
                                <!-- <select type="text" class="form-control" name="customer_county"></select> -->
                                {{ form.customer_county }}
                            </div>
                            <div class="col-lg-2 col-md-2, col-sm-3" style="float: right; margin-top: 5px;">
                                <label></label>
                                <div>                                        
                                    <button class="btn btn-primary col-md-6" type="submit" id="submitBtn">搜索</button>
                                    <button class="btn btn-white col-md-3" type="reset" style="float: right;" id="resetBtn">重置</button>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
        <div class="ibox ">
            <div class="ibox-content">

                <div class="jqGrid_wrapper">
                    <table id="table_list_1"></table>
                    <div id="pager_list_1"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="init-data" style="display: none;">{{ init_data }}</div>
{% endblock %}

{% block js_tail %}
    <!-- Peity -->
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>

    <!-- jqGrid -->
    <script src="{% static 'js/plugins/jqgrid/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/jquery.jqGrid.min.js' %}"></script>
    <script src="{% static 'js/content.js' %}"></script>
    <script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'js/plugins/jsKnob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'js/customer/industry_coverage_list.js' %}"></script>
{% endblock %}