notice/urls.py
from django.urls import re_path, path

from notice import views

urlpatterns = [
    re_path(r'^list$', views.notice_list, name="notice_list"),
    re_path(r'^list/api$', views.notice_list_api, name="notice_list_api"),
    re_path(r'^list/export$', views.export_notice_list, name="export_notice_list"),
    
    re_path(r'^settings$', views.notice_settings, name="notice_settings"),
    re_path(r'^settings/change$', views.change_notice_setting, name="change_notice_setting"),
    re_path(r'^setting/list/api$', views.notice_setting_list_api, name="notice_setting_list_api"),
]

app_name = "notice"

sale/urls.py
from django.urls import re_path, path

from sale import views

urlpatterns = [
    re_path(r'^index$', views.sale_index, name="sale_index"),
    re_path(r'^data/customer/all$', views.get_data_customer_all, name="data_customer_all"),
    re_path(r'^data/customer/day$', views.get_data_customer_day, name="data_customer_day"),
    re_path(r'^data/money/all$', views.get_data_money_all, name="data_money_all"),
    re_path(r'^data/money/day$', views.get_data_money_day, name="data_money_day"),

    # re_path(r'^goal/regionals/year/api$', views.goal_regionals_year_api, name="goal_regionals_year_api"),
    re_path(r'^goal/regionals/month/api$', views.goal_regionals_month_api, name="goal_regionals_month_api"),

    re_path(r'^payment/company/months/api$', views.payment_company_months_api, name="payment_company_months_api"),
    re_path(r'^payment/company/days/api$', views.payment_company_days_api, name="payment_company_days_api"),

    re_path(r'^saler/list$', views.saler_list, name="saler_list"),
    re_path(r'^saler/list/api$', views.saler_list_api, name="saler_list_api"),
    re_path(r'^saler/info/list/api$', views.saler_info_list_api, name="saler_info_list_api"),
    
    re_path(r'^saler/list/export$', views.export_saler_list, name="export_saler_list"),

    re_path(r'^payment/plan/list$', views.payment_plan_list, name="payment_plan_list"),
    re_path(r'^payment/plan/list/api$', views.payment_plan_list_api, name="payment_plan_list_api"),
    # re_path(r'^payment/plan/list/export$', views.export_payment_plan_list, name="export_payment_plan_list"),

    re_path(r'^portrait/saler$', views.saler_portrait, name="saler_portrait"),
    re_path(r'^portrait/saler/1$', views.saler_portrait1, name="saler_portrait1"),
    re_path(r'^portrait/saler/2$', views.saler_portrait2, name="saler_portrait2"),
    re_path(r'^portrait/saler/3$', views.saler_portrait3, name="saler_portrait3"),
    re_path(r'^data/work/daily$', views.get_data_work_daily, name="data_work_daily"),

    re_path(r'^portrait/fuzzy$', views.fuzzy_portrait, name="fuzzy_portrait"),
    re_path(r'^portrait/region$', views.region_portrait, name="region_portrait"),
    re_path(r'^portrait/department$', views.department_portrait, name="department_portrait"),

    re_path(r'^analysis$', views.opp_analysis, name="opp_analysis"),
    re_path(r'^analysis/tableapi$', views.get_opptable_info, name="opp_tableapi"),
    re_path(r'^analysis/allapi$', views.get_opp_info, name="opp_allapi"),
    re_path(r'^analysis/api$', views.get_oppt_info_single, name="opp_api"),

    re_path(r'^dingding/government/center$', views.dingding_government_center, name="dingding_government_center"),
    re_path(r'^dingding/government/center/tab$', views.dingding_government_center_tab, name="dingding_government_center_tab"),
    re_path(r'^dingding/government/center/table$', views.dingding_government_center_table, name="dingding_government_center_table"),

    re_path(r'^dingding/department/frame/api$', views.dingding_department_frame_api, name="dingding_department_frame_api"),
    re_path(r'^dingding/region/frame/members/api$', views.dingding_region_frame_members_api, name="dingding_region_frame_members_api"),
    re_path(r'^dingding/department/frame/members/api$', views.dingding_department_frame_members_api, name="dingding_department_frame_members_api"),

    re_path(r'^customer/count/sale/center/api$', views.customer_count_sale_center_api, name="customer_count_sale_center_api"),
    re_path(r'^customer/count/region/api$', views.customer_count_region_api, name="customer_count_region_api"),
    re_path(r'^customer/count/department/api$', views.customer_count_department_api, name="customer_count_department_api"),
    re_path(r'^customer/count/saler/api$', views.customer_count_saler_api, name="customer_count_saler_api"),
    re_path(r'^work/daily/department/api$', views.work_daily_department_api, name="work_daily_department_api"),
    re_path(r'^work/daily/department/salers/api$', views.work_daily_department_salers_api, name="work_daily_department_salers_api"),
    re_path(r'^payment/department/days/api$', views.payment_department_days_api, name="payment_department_days_api"),
    re_path(r'^goal/regions/month/api$', views.goal_regions_month_api, name="goal_regions_month_api"),
    re_path(r'^goal/departments/month/api$', views.goal_departments_month_api, name="goal_departments_month_api"),
    re_path(r'^goal/salers/month/api$', views.goal_salers_month_api, name="goal_salers_month_api"),
    re_path(r'^account/count/api$', views.account_count_api, name="account_count_api"),
    re_path(r'^products/account/count/api$', views.products_account_count_api, name="products_account_count_api"),
    re_path(r'^opportunity/count/api$', views.opportunity_count_api, name="opportunity_count_api"),

    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^saler/info/api$', views.saler_info_api, name="saler_info_api"),
    re_path(r'^work/daily/saler/api$', views.work_daily_saler_api, name="work_daily_saler_api"),
    re_path(r'^goal/saler/month/api$', views.goal_saler_month_api, name="goal_saler_month_api"),

    re_path(r'^customer/list/api$', views.customer_list_api, name="sale_customer_list_api"),
    re_path(r'^opportunity/list/api$', views.opportunity_list_api, name="sale_opportunity_list_api"),
    re_path(r'^opportunity$', views.opportunity_info_api, name="sale_opportunity_api"),
    re_path(r'^opportunity/info/api$', views.opportunity_info_api, name="sale_opportunity_info_api"),

    re_path(r'^test$', views.test, name="test"),
    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^tenders/info/api$', views.Tenders.as_view(), name="tenders_info_api"),

    re_path(r'^saler/kpi/overview$', views.saler_kpi_overview, name="saler_kpi_overview"),
    re_path(r'^saler/kpi/overview/api$', views.saler_kpi_overview_api, name="saler_kpi_overview_api"),
    re_path(r'^saler/kpi/month$', views.saler_kpi_month, name="saler_kpi_month"),
    re_path(r'^saler/kpi/month/api$', views.saler_kpi_month_api, name="saler_kpi_month_api"),
    re_path(r'^saler/kpi/month/export$', views.export_saler_kpi_month, name="export_saler_kpi_month"),
    re_path(r'^saler/kpi/history$', views.saler_kpi_history, name="saler_kpi_history"),
    re_path(r'^saler/kpi/history/api$', views.saler_kpi_history_api, name="saler_kpi_history_api"),
    re_path(r'^saler/kpi/history/export$', views.export_saler_kpi_history, name="export_saler_kpi_history"),
]

app_name = "sale"

support/urls.py
# from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings
from support import views


urlpatterns = [
    # path('admin/', admin.site.urls),
    # re_path(r'^center/', include('center.urls'), name='center'),

    re_path(r'^', include('user_center.urls'), name='user_center'),
    re_path('^customer/', include('customer.urls', namespace="customer")),
    re_path('^secretary/', include('secretary.urls', namespace="secretary")),
    re_path('^(.+)\.html', views.show_html),
    re_path('^json/403$', views.json_403),
    re_path('^competitor/', include('competitor.urls')),
    re_path('^sale/', include('sale.urls')),
    re_path('^notice/', include('notice.urls')),
    re_path('^statistical/', include('statistical.urls')),
    re_path('^visit/', include('salerVisit.urls')),
    re_path('^work_platform/', include('work_platform.urls')),

    re_path(r'^xman/', include('xman.urls'), name='xman'),
    re_path('^mobile_cloud/', include('mobile_cloud.urls')),
    re_path('^financial_statements/', include('financial_statements.urls')),
    re_path('^user_log/', include('user_log.urls')),
    re_path('^product/', include('product.urls')),
    re_path('^interface/', include('interface.urls')),
]

# This will work if DEBUG is True

urlpatterns += staticfiles_urlpatterns() #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError

from public.utils import get_value_list
from notice.models import NoticeList, NoticeSetting, NoticeType
from notice.apps import NoticeConfig

"""钉钉通知消息筛选表单"""
class NoticeListSelectForm(forms.Form):
    ding_user = forms.CharField(label='用户：', max_length=100, required=False, widget=forms.TextInput())
    notice_type = forms.CharField(label='消息类型：', required=False, widget=forms.Select(
        choices=[("", "--------")], 
        attrs={"type": "text", "class": "form-control", "style": "padding-top: 2px;"}
    ))
    content = forms.CharField(label='消息内容：', max_length=100, required=False, widget=forms.TextInput())
    department = forms.CharField(label='部门：', max_length=100, required=False, widget=forms.TextInput())
    status = forms.CharField(label='发送状态：', required=False, widget=forms.Select(
        choices=[("", "--------")] + list(NoticeConfig.notice_sending_status_choices), 
        attrs={"type": "text", "class": "form-control", "style": "padding-top: 2px;"}
    ))

    # 重写父类的 __init__ 方法
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['notice_type'].widget.choices = [("", "--------")] + get_value_list(NoticeType, {}, ["id", "name"])

"""消息设置表单"""
class NoticeSettingForm(forms.Form):
    ding_user_id = forms.CharField(label='用户钉ID', required=False)
    notice_type_id = forms.CharField(label='消息类型：', required=True, widget=forms.Select(
        choices=[("", "--------")], 
        attrs={"type": "text", "class": "form-control", "style": "padding-top: 2px;"}
    ))
    status = forms.IntegerField(label="是否接收消息", required=True)

    # 重写父类的 __init__ 方法
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['notice_type_id'].widget.choices = [("", "--------")] + get_value_list(NoticeType, {}, ["id", "name"])

notice/views/notice_list.py
import json
import arrow
import logging

from django.http import  JsonResponse
from django.shortcuts import render
from mandala.auth import get_user_model
from mandala.auth.decorators import  permission_required,login_required
from notice.forms import NoticeListSelectForm
from notice.models import NoticeList
from notice.apps import NoticeConfig
from user_center.models import UserLog
from secretary.models import SalercanseeNew

from django.conf import settings
URL_403 = settings.URL_403
JSON_403 = settings.JSON_403
# Create your views here.
app_name = "notice"
logger = logging.getLogger(app_name)

User = get_user_model()

"""获取钉钉通知消息列表页面初始数据"""
def get_notice_list_init_data():
    init_data = {"row_list": [10, 20, 50], "row_num": 20}
    init_data["col_names"] = ["用户", "消息内容", "消息类型", "发送时间", "发送状态"]
    init_data["col_model"] = [
        {
            "name": 'ding_user__username',
            # "index": 'note',
            "width": 6,
            # "sortable": false
        },
        {
            "name": 'content',
            # "index": 'note',
            "width": 60,
            # "sortable": false
        },
        {
            "name": 'notice_type__name',
            # "index": 'id',
            "width": 12,
            # "sorttype": "int"
        },
        {
            "name": 'ctime',
            # "index": 'tax',
            "width": 10,
            # "sortable": false
        },
        {
            "name": 'status',
            # "index": 'tax',
            "width": 6,
            # "sortable": false
        }
    ]
    init_data["items"] = []
    return init_data

"""通知消息列表页面"""
@login_required()
@permission_required("notice.notice_list.view",login_url=URL_403)
def notice_list(request):
    if request.method == "GET":

        message = json.dumps(dict(request.GET))
        UserLog.objects.create(username=request.user.username, user_id=request.user.id,
                model="通知管理-通知列表", action="访问", message=message)

        title = "钉钉通知消息列表"
        form = NoticeListSelectForm(request.GET)
        init_data = get_notice_list_init_data()
        # if request.user.has_perm("notice.export_notice_list"):
        #     init_data["export_notice_list_access"] = 1

        init_data = json.dumps(init_data)
        # user_log_url = reverse("user_center:user_log")
        # departments_api = reverse("secretary:departments_api")
        # department_data = get_departments_about_sale()
        # department_data = json.dumps(department_data)
        # department_data_1 =[["", "--------"]] + list(settings.SALE_DEPARTMENT_LEVEL_1.items())
        # department_data_1 = json.dumps(department_data_1)
        return render(request, "notice/notice_list.html", locals())

"""接口：获取钉钉消息通知信息列表"""
@login_required()
@permission_required("notice.notice_list.view",login_url=JSON_403)
def notice_list_api(request):
    result = {"code": 0, "msg": ""}
    if request.method == "GET":
        kws = request.GET
    else:
        kws = request.POST

    message = json.dumps(dict(kws))
    UserLog.objects.create(username=request.user.username, user_id=request.user.id,
            model="通知管理-通知列表api", action="查询", message=message)

    form = NoticeListSelectForm(kws)
    if not form.is_valid():
        result["code"] = -1
        result["msg"] = "参数错误"
    # 根据输入的商务名查询数据
    cdata = form.cleaned_data
    ding_user = cdata.get("ding_user")
    params = {}

    # 查询数据权限
    cansee_users = json.loads(
        SalercanseeNew.objects.filter(saleid=request.user.istarshine_id).values_list('cansee', flat=True).first())
    # print(cansee_users)

    cansee_users_obj = list(User.objects.filter(istarshine_id__in=cansee_users))
    if ding_user:
        # 如果有筛选条件，模糊查询
        ding_users = list(User.objects.filter(username__icontains=ding_user))
        # print(ding_users)
        if not ding_users:
            result["msg"] = "查无此人"
            return JsonResponse(result)
        else:
            # 如果是超管，按照模糊查询结果查
            if request.user.is_superuser:
                ding_users = ding_users
            else:
                # 非超管，需要和cansee表结果取交集
                ding_users_obj = list(set(ding_users)&set(cansee_users_obj))
                if not ding_users_obj:
                    result["msg"] = "您没有权限"
                    return JsonResponse(result)
                else:
                    ding_users = ding_users_obj
    else:
        # 如果是超管
        if request.user.is_superuser:
            ding_users = None
        else:
            ding_users = cansee_users_obj


    if ding_users:
        params["ding_user__in"] = ding_users

    # 根据消息内容查询数据
    content = cdata.get("content")
    if content:
        params["content__icontains"] = content

    # 根据发送状态查询数据
    status = cdata.get("status")
    if status:
        params["status"] = status

    # 根据消息类型查询数据
    notice_type = cdata.get("notice_type")
    if notice_type:
        params["notice_type"] = notice_type

    fields = ["ding_user__username", 'notice_type__name']
    for field in NoticeList._meta.fields:
        fields.append(field.name)

    _items = NoticeList.objects.filter(**params).values(*fields).order_by("-id")
    items = []
    status_map = dict(NoticeConfig.notice_sending_status_choices)
    for item in _items:
        ctime = item.get("ctime")
        if ctime:
            ctime = arrow.get(ctime).datetime.strftime("%Y-%m-%d %H:%M:%S")
        else:
            ctime = "--------"
        item["ctime"] = ctime
        item["status"] = status_map.get(item["status"], "--------")
        items.append(item)
    result["data"] = items
    result["code"] = 1
    return JsonResponse(result)

"""导出钉钉消息通知列表"""
@login_required()
@permission_required("notice.notice_list.export",login_url=JSON_403)
def export_notice_list(request):

    message = json.dumps(dict(request.GET))
    UserLog.objects.create(username=request.user.username, user_id=request.user.id,
            model="通知管理-通知列表", action="导出", message=message)

    return JsonResponse({})

templates/notice/notice_list.html
{% extends 'base.html' %}
{% load i18n static %}

{% block css_tail %}
<!-- jqgrid-->
<link href="{% static 'css/plugins/jqgrid/ui.jqgrid.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<script>

</script>
<div style="display: none;">
    <div id="department-api">{{ departments_api }}</div>
    <div id="department-data">{{ department_data }}</div>
    <div id="department-data-1">{{ department_data_1 }}</div>
    <div id="search-data-api">{% url 'notice:notice_list_api' %}</div>
    <div id="fields-to-check">{{ fields_to_check }}</div>
    <div id="user-log-url">{{ user_log_url }}</div>
    <div id="export-file">{% url 'notice:export_notice_list' %}</div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div style="margin-top: 10px;"></div>
        <div class="ibox float-e-margins" style="margin-bottom: 10px;">
            <div class="ibox-content">
                <form method="GET" onsubmit="return false;" class="form-horizontal" id="search-form">
                    <!-- {% csrf_token %} -->
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="col-lg-2 col-md-3 col-sm-6" style="margin-top: 5px;">
                                <label><nobr>用户：</nobr></label>
                                <input type="text" class="form-control" placeholder="模糊查询" name="ding_user">
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6" style="margin-top: 5px;">
                                <label><nobr>消息类型：</nobr></label>
                                {{ form.notice_type }}
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-6" style="margin-top: 5px;">
                                <label><nobr>消息内容：</nobr></label>
                                <input type="text" class="form-control" placeholder="模糊查询"  name="content"/>
                            </div>
                            <div class="col-lg-1 col-md-2 col-sm-3" style="margin-top: 5px;">
                                <label><nobr>发送状态：</nobr></label>
                                {{ form.status }}
                            </div>
                            <!-- <div class="col-lg-2 col-md-2 col-sm-3" style="margin-top: 5px; display: none;">
                                <input name="department" id="department-value" />
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3" id="id_department-1" style="margin-top: 5px;">
                                <label><nobr>部门：</nobr></label>
                                <select type="text" class="form-control" id="department-1" onchange="onDepartmentChange1()" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3" id="id_department-2" style="margin-top: 5px; display: none;">
                                <label><nobr>二级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-2" onchange="onDepartmentChange2()" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3" id="id_department-3" style="margin-top: 5px; display: none;">
                                <label><nobr>三级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-3" onchange="onDepartmentChange3()" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3" id="id_department-4" style="margin-top: 5px; display: none;">
                                <label><nobr>四级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-4" onchange="onDepartmentChange4()" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3" id="id_department-5" style="margin-top: 5px; display: none;">
                                <label><nobr>五级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-5" onchange="onDepartmentChange5()" style="padding-top: 2px;"></select>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-3" id="id_department-6" style="margin-top: 5px; display: none;">
                                <label><nobr>六级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-6" onchange="onDepartmentChange6()"></select>
                            </div>
                            <div class="col-md-2 col-sm-2" id="id_department-7" style="margin-top: 5px; display: none;">
                                <label><nobr>七级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-7" onchange="onDepartmentChange7()"></select>
                            </div>
                            <div class="col-md-1 col-sm-2" id="id_department-8" style="margin-top: 5px; display: none;">
                                <label><nobr>八级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-8" onchange="onDepartmentChange8()"></select>
                            </div>
                            <div class="col-md-1 col-sm-2" id="id_department-9" style="margin-top: 5px; display: none;">
                                <label><nobr>九级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-9" onchange="onDepartmentChange9()"></select>
                            </div>
                            <div class="col-md-1 col-sm-2" id="id_department-10" style="margin-top: 5px; display: none;">
                                <label><nobr>十级部门:</nobr></label>
                                <select type="text" class="form-control" id="department-10" onchange="onDepartmentChange10()"></select>
                            </div> -->
                            
                            <div class="col-lg-2 col-md-4 col-sm-6" style="float: right; margin-top: 5px;">
                                <label></label>
                                <div>                                        
                                    <button class="btn btn-primary col-md-6 col-sm-6" type="submit" id="submitBtn">搜索</button>
                                    <button class="btn btn-white col-md-5 col-sm-4" type="reset" style="float: right;" id="resetBtn">重置</button>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
        <div class="ibox ">
            <div class="ibox-content">

                <div class="jqGrid_wrapper">
                    <table id="table_list_1"></table>
                    <div id="pager_list_1"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="init-data" style="display: none;">{{ init_data }}</div>
{% endblock %}

{% block js_tail %}
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/jquery.jqGrid.min.js' %}"></script>
    <script src="{% static 'js/content.js' %}"></script>
    <script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'js/plugins/jsKnob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'js/notice/notice_list.html.js' %}"></script>
{% endblock %}

templates/notice/notice_settings.html
{% extends 'base.html' %}
{% load i18n static %}

{% block css_tail %}
<link rel="stylesheet" href="{% static 'css/element-ui@2.13.1/lib/theme-chalk/index.css' %}">
{% endblock %}

{% block body %}

<script src="{% static 'js/npm/vue@2.6.11' %}"></script>
<script src="{% static 'js/axios/dist/axios.min.js' %}"></script>
<script src="{% static 'js/element-ui@2.13.1/lib/index.js' %}"></script>


<style>
    .el-row {
      margin-bottom: 20px;
      &:last-child {
        margin-bottom: 0;
      }
    }
    .el-col {
      border-radius: 4px;
    }
    .bg-purple-dark {
      background: #99a9bf;
    }
    .bg-purple {
      background: #d3dce6;
    }
    .bg-purple-light {
      background: #e5e9f2;
    }
    .grid-content {
      border-radius: 4px;
      min-height: 36px;
    }
    .row-bg {
      padding: 10px 0;
      background-color: #f9fafc;
    }
  </style>
<div style="display: none;">
</div>
<div class="row" style="margin: 0; height: 100%;">
    <div class="col-sm-12" style="margin: 0; height: 100%;">
        <div style="margin-top: 10px;"></div>
        <div class="ibox float-e-margins" style="margin: 0; height: 100%;">
            <div class="ibox-content" style="margin: 0; height: 100%;">
                <!-- {% for ns in notice_setting_list %}
                    <form method="GET" onsubmit="return false;" class="form-horizontal" id="setting-form-{{ ns.notice_type_id }}">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-10 col-lg-8 col-xl-6 col-md-offset-1 col-lg-offset-2 col-xl-offset-3">
                                <div class="col-sm-12" style="margin-top: 5px;">
                                    <input style="display: none;" name="ding_user_id" value="{{ request.user.dtalkid }}" />
                                    <span style="font-size: large;" class="col-sm-6" title="{{ ns.comment }}"><nobr>{{ forloop.counter }}、{{ ns.name }}：</nobr></span>
                                    <span class="col-sm-2">
                                        <input type="checkbox" class="js-switch js-check-change" 
                                            data-switchery="true" style="display: none;" 
                                            checked="{% if ns.status %}true{% else %}false{% endif %}" />
                                    </span>
                                    <span style="font-size: large;" class="check-change js-check-change-field col-sm-4">{% if ns.status %}已开启{% else %}已禁用{% endif %}</span>
                                </div>
                            </div>
                        </div>
                    </form>
                {% endfor %} -->
                <div id="main" v-if="ok">
                    <template v-for="(setting, index) in settings">
                        <el-row :gutter="20">
                            <el-col :span="4"><div class="grid-content"></div></el-col>
                            <el-col :span="12">
                                <div class="grid-content" :title="setting.comment">
                                    [[ index + 1 ]]、[[ setting.name ]]
                                </div>
                            </el-col>
                            <el-col :span="4">
                                <div class="grid-content">
                                    <el-switch
                                        v-model="setting.status"
                                        active-color="#13ce66"
                                        inactive-color="#ff4949"
                                        @change="changeSwitch(setting)">
                                    </el-switch>
                                    <template v-if="setting.status">已开启</template>
                                    <template v-else>已关闭</template>
                                </div>
                            </el-col>
                            <el-col :span="4"><div class="grid-content"></div></el-col>
                        </el-row>
                    </template>
                    <!-- <template v-for="setting in settings">
                        <el-switch
                            v-model="setting.status"
                            on-color="#00A854"
                            on-text="启动"
                            on-value="1"
                            off-color="#F04134"
                            off-text="禁止"
                            off-value="0"
                            @change="changeSwitch(setting)">
                        </el-switch>
                    </template> -->
                </div>
            </div>
        </div>
    </div>
</div>
<div id="init-data" style="display: none;">{{ init_data }}</div>
{% endblock %}

{% block js_tail %}
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/jquery.jqGrid.min.js' %}"></script>
    <script src="{% static 'js/content.js' %}"></script>
    <script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'js/plugins/jsKnob/jquery.knob.js' %}"></script>
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>
    <!-- <script src="{% static 'js/notice/notice_settings.html.js' %}"></script> -->
    <script src="{% static 'js/notice/notice_settings.js' %}"></script>
{% endblock %}