competitor/urls.py
from django.urls import re_path, path

from competitor import views

urlpatterns = [
    # 竞品列表页面的url,侧边栏调用
    re_path(r'^competitorList$', views.competitorList, name="competitor_list"),

    # 设置竞品签约客户页面的url,侧边栏调用
    re_path(r'^competitorCrm$', views.competitorCrm, name="competitor_crm"),

    # 竞品签约客户的列表加载数据接口
    re_path(r'^api/competitorCrm$', views.competitorCrmListApi, name="competitor_api"),

    # 操作竞品的接口,获取竞品列表数据、添加竞品、删除竞品、修改竞品
    re_path(r'^api/operate_competitor$', views.OperateCompetitor.as_view(), name="operate_competitor"),

    # 关联竞品的接口，关联、删除关联关系、修改关联的信息
    re_path(r'^api/connect_competitor$', views.connect_competitor_api, name="connect_competitor_api"),

    # 更新关联竞品页面的下拉框选项值
    re_path(r'^api/updateSelectForm$', views.updateSelectForm, name="updateSelectForm_api"),

    # 竞品分析页面
    re_path(r'^analysis$', views.analysis, name="competitor_analysis"),
    # 客户占有分析
    re_path(r'^occupiedAnalysis$', views.occupiedAnalysis, name="occupied"),
    # 签单金额分析
    re_path(r'^moneyAnalysis$', views.moneyAnalysis, name="money"),
    # 签单地域分析
    re_path(r'^localAnalysis$', views.localAnalysis, name="local"),
    # 签单行业分析
    re_path(r'^industryAnalysis$', views.industryAnalysis, name="industry"),
    re_path(r'^industry2Analysis$', views.industry2Analysis, name="industry2money"),
    # 计算签单客户的状态
    re_path(r'^customerStatus$', views.UpdateStatus.as_view(), name="customerStatus"),


    re_path(r'^getIP$', views.getIP, name="getIP$"),

]

app_name = "competitor"

sale/urls.py
from django.urls import re_path, path

from sale import views

urlpatterns = [
    re_path(r'^index$', views.sale_index, name="sale_index"),
    re_path(r'^data/customer/all$', views.get_data_customer_all, name="data_customer_all"),
    re_path(r'^data/customer/day$', views.get_data_customer_day, name="data_customer_day"),
    re_path(r'^data/money/all$', views.get_data_money_all, name="data_money_all"),
    re_path(r'^data/money/day$', views.get_data_money_day, name="data_money_day"),

    # re_path(r'^goal/regionals/year/api$', views.goal_regionals_year_api, name="goal_regionals_year_api"),
    re_path(r'^goal/regionals/month/api$', views.goal_regionals_month_api, name="goal_regionals_month_api"),

    re_path(r'^payment/company/months/api$', views.payment_company_months_api, name="payment_company_months_api"),
    re_path(r'^payment/company/days/api$', views.payment_company_days_api, name="payment_company_days_api"),

    re_path(r'^saler/list$', views.saler_list, name="saler_list"),
    re_path(r'^saler/list/api$', views.saler_list_api, name="saler_list_api"),
    re_path(r'^saler/info/list/api$', views.saler_info_list_api, name="saler_info_list_api"),
    
    re_path(r'^saler/list/export$', views.export_saler_list, name="export_saler_list"),

    re_path(r'^payment/plan/list$', views.payment_plan_list, name="payment_plan_list"),
    re_path(r'^payment/plan/list/api$', views.payment_plan_list_api, name="payment_plan_list_api"),
    # re_path(r'^payment/plan/list/export$', views.export_payment_plan_list, name="export_payment_plan_list"),

    re_path(r'^portrait/saler$', views.saler_portrait, name="saler_portrait"),
    re_path(r'^portrait/saler/1$', views.saler_portrait1, name="saler_portrait1"),
    re_path(r'^portrait/saler/2$', views.saler_portrait2, name="saler_portrait2"),
    re_path(r'^portrait/saler/3$', views.saler_portrait3, name="saler_portrait3"),
    re_path(r'^data/work/daily$', views.get_data_work_daily, name="data_work_daily"),

    re_path(r'^portrait/fuzzy$', views.fuzzy_portrait, name="fuzzy_portrait"),
    re_path(r'^portrait/region$', views.region_portrait, name="region_portrait"),
    re_path(r'^portrait/department$', views.department_portrait, name="department_portrait"),

    re_path(r'^analysis$', views.opp_analysis, name="opp_analysis"),
    re_path(r'^analysis/tableapi$', views.get_opptable_info, name="opp_tableapi"),
    re_path(r'^analysis/allapi$', views.get_opp_info, name="opp_allapi"),
    re_path(r'^analysis/api$', views.get_oppt_info_single, name="opp_api"),

    re_path(r'^dingding/government/center$', views.dingding_government_center, name="dingding_government_center"),
    re_path(r'^dingding/government/center/tab$', views.dingding_government_center_tab, name="dingding_government_center_tab"),
    re_path(r'^dingding/government/center/table$', views.dingding_government_center_table, name="dingding_government_center_table"),

    re_path(r'^dingding/department/frame/api$', views.dingding_department_frame_api, name="dingding_department_frame_api"),
    re_path(r'^dingding/region/frame/members/api$', views.dingding_region_frame_members_api, name="dingding_region_frame_members_api"),
    re_path(r'^dingding/department/frame/members/api$', views.dingding_department_frame_members_api, name="dingding_department_frame_members_api"),

    re_path(r'^customer/count/sale/center/api$', views.customer_count_sale_center_api, name="customer_count_sale_center_api"),
    re_path(r'^customer/count/region/api$', views.customer_count_region_api, name="customer_count_region_api"),
    re_path(r'^customer/count/department/api$', views.customer_count_department_api, name="customer_count_department_api"),
    re_path(r'^customer/count/saler/api$', views.customer_count_saler_api, name="customer_count_saler_api"),
    re_path(r'^work/daily/department/api$', views.work_daily_department_api, name="work_daily_department_api"),
    re_path(r'^work/daily/department/salers/api$', views.work_daily_department_salers_api, name="work_daily_department_salers_api"),
    re_path(r'^payment/department/days/api$', views.payment_department_days_api, name="payment_department_days_api"),
    re_path(r'^goal/regions/month/api$', views.goal_regions_month_api, name="goal_regions_month_api"),
    re_path(r'^goal/departments/month/api$', views.goal_departments_month_api, name="goal_departments_month_api"),
    re_path(r'^goal/salers/month/api$', views.goal_salers_month_api, name="goal_salers_month_api"),
    re_path(r'^account/count/api$', views.account_count_api, name="account_count_api"),
    re_path(r'^products/account/count/api$', views.products_account_count_api, name="products_account_count_api"),
    re_path(r'^opportunity/count/api$', views.opportunity_count_api, name="opportunity_count_api"),

    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^saler/info/api$', views.saler_info_api, name="saler_info_api"),
    re_path(r'^work/daily/saler/api$', views.work_daily_saler_api, name="work_daily_saler_api"),
    re_path(r'^goal/saler/month/api$', views.goal_saler_month_api, name="goal_saler_month_api"),

    re_path(r'^customer/list/api$', views.customer_list_api, name="sale_customer_list_api"),
    re_path(r'^opportunity/list/api$', views.opportunity_list_api, name="sale_opportunity_list_api"),
    re_path(r'^opportunity$', views.opportunity_info_api, name="sale_opportunity_api"),
    re_path(r'^opportunity/info/api$', views.opportunity_info_api, name="sale_opportunity_info_api"),

    re_path(r'^test$', views.test, name="test"),
    re_path(r'^department/info/api$', views.department_info_api, name="department_info_api"),
    re_path(r'^tenders/info/api$', views.Tenders.as_view(), name="tenders_info_api"),

    re_path(r'^saler/kpi/overview$', views.saler_kpi_overview, name="saler_kpi_overview"),
    re_path(r'^saler/kpi/overview/api$', views.saler_kpi_overview_api, name="saler_kpi_overview_api"),
    re_path(r'^saler/kpi/month$', views.saler_kpi_month, name="saler_kpi_month"),
    re_path(r'^saler/kpi/month/api$', views.saler_kpi_month_api, name="saler_kpi_month_api"),
    re_path(r'^saler/kpi/month/export$', views.export_saler_kpi_month, name="export_saler_kpi_month"),
    re_path(r'^saler/kpi/history$', views.saler_kpi_history, name="saler_kpi_history"),
    re_path(r'^saler/kpi/history/api$', views.saler_kpi_history_api, name="saler_kpi_history_api"),
    re_path(r'^saler/kpi/history/export$', views.export_saler_kpi_history, name="export_saler_kpi_history"),
]

app_name = "sale"

support/urls.py
# from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings
from support import views


urlpatterns = [
    # path('admin/', admin.site.urls),
    # re_path(r'^center/', include('center.urls'), name='center'),

    re_path(r'^', include('user_center.urls'), name='user_center'),
    re_path('^customer/', include('customer.urls', namespace="customer")),
    re_path('^secretary/', include('secretary.urls', namespace="secretary")),
    re_path('^(.+)\.html', views.show_html),
    re_path('^json/403$', views.json_403),
    re_path('^competitor/', include('competitor.urls')),
    re_path('^sale/', include('sale.urls')),
    re_path('^notice/', include('notice.urls')),
    re_path('^statistical/', include('statistical.urls')),
    re_path('^visit/', include('salerVisit.urls')),
    re_path('^work_platform/', include('work_platform.urls')),

    re_path(r'^xman/', include('xman.urls'), name='xman'),
    re_path('^mobile_cloud/', include('mobile_cloud.urls')),
    re_path('^financial_statements/', include('financial_statements.urls')),
    re_path('^user_log/', include('user_log.urls')),
    re_path('^product/', include('product.urls')),
    re_path('^interface/', include('interface.urls')),
]

# This will work if DEBUG is True

urlpatterns += staticfiles_urlpatterns() #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

competitor/forms.py
from django import forms
from customer.utils import get_states
from competitor.utils import *


class CompetitorSelectForm(forms.Form):
    '''竞品签约客户列表发筛选form表单'''
    customer_name = forms.CharField(label='客户名称：', max_length=100, required=False, widget=forms.TextInput())
    customer_province = forms.CharField(label='客户地域-省：', required=False, widget=forms.Select(
        choices=[("", "--------")],
        attrs={
            "type": "text", 
            "class": "form-control", 
            "style": "padding-top: 2px;",
            # "onchange": "onProvinceChange()"
            }
    ))

    competitor_name = forms.CharField(label='竞品名称：', max_length=100, required=False,
                                      widget=forms.TextInput(attrs={"class":"form-control","placeholder":"模糊查询"}))
    saler = forms.CharField(label='商务：', max_length=100, required=False, widget=forms.TextInput())
    service_time_start = forms.CharField(label='竞品服务开始日期：', max_length=100, required=False, widget=forms.TextInput(
        attrs={"placeholder": "----------"}
    ))
    service_time_finish = forms.CharField(label='竞品服务结束日期：', max_length=100, required=False, widget=forms.TextInput(
        attrs={"placeholder": "----------"}
    ))
    no_service_time = forms.CharField(label='无竞品服务日期：', required=False, widget=forms.CheckboxInput())
    department = forms.CharField(label='部门：', max_length=100, required=False, widget=forms.TextInput())

    competitorId = forms.CharField(label='竞品名称：', required=False, widget=forms.Select(
        choices=[("", "--------")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;",
            # "onchange": "onProvinceChange()"
        }
    ))
    competitorProductId = forms.CharField(label='签单产品：', required=False, widget=forms.Select(
        choices=[("", "--------")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;",
            # "onchange": "onProvinceChange()"
        }
    ))
    industry_1 = forms.CharField(label='一级行业：', required=False, widget=forms.Select(
        choices=[("", "全部")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;",
            "onchange": "onIndustryChange1()"
        }
    ))
    industry_2 = forms.CharField(label='二级行业：', required=False, widget=forms.Select(
        choices=[("", "全部")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;"
        }
    ))
    # industry1 = forms.CharField(label='一级行业：', max_length=100, required=False, widget=forms.TextInput())
    # industry2 = forms.CharField(label='二级行业：', max_length=100, required=False, widget=forms.TextInput())

    # 重写父类的 __init__ 方法
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['lang_code'].widget.choices = [("", "--------")] + language_list
        self.fields['customer_province'].widget.choices = [("", "全国")] + get_states()
        self.fields['competitorId'].widget.choices = [("", "全部")] + get_competitor()
        self.fields['competitorProductId'].widget.choices = [("", "全部")] + get_product()

        self.fields['industry_1'].widget.choices = [("", "全部")] + get_industry_l1_list()
        self.fields['industry_2'].widget.choices = [("", "全部")] + get_industry_l2_list()

    def select_province(self,id):
        # 默认省份为河北省
        self.initial["customer_province"] = id

    def input_competitorName(self,name):
        # 根据请求带的条件赋值
        self.initial['competitor_name'] = name

    def select_industry1(self,id):
        # 根据行业id设置行业
        self.initial["industry_1"] = id

    def select_industry2(self,id):
        # 根据行业id设置行业
        self.initial["industry_2"] = id



class CompetitorListSelectForm(forms.Form):
    '''竞品列表页面的form表单'''
    competitor_name = forms.CharField(label='竞品名称：', max_length=100, required=False, widget=forms.TextInput())
    customer_name = forms.CharField(label='客户名称：', max_length=100, required=False, widget=forms.TextInput())
    customer_province = forms.CharField(label='签单地域：', required=False, widget=forms.Select(
        choices=[("", "全国")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;",
            # "onchange": "onProvinceChange()"
            }
    ))
    industry_1 = forms.CharField(label='一级行业：', required=False, widget=forms.Select(
        choices=[("", "全部")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;",
            "onchange": "onDepartmentChange1()"
            }
    ))
    industry_2 = forms.CharField(label='二级行业：', required=False, widget=forms.Select(
        choices=[("", "全部")],
        attrs={
            "type": "text",
            "class": "form-control",
            "style": "padding-top: 2px;",
            # "onchange": "onDepartmentChange1()"
        }
    ))
    # industry1 = forms.CharField(label='一级行业：', max_length=100, required=False, widget=forms.TextInput())
    # industry2 = forms.CharField(label='二级行业：', max_length=100, required=False, widget=forms.TextInput())

    # 重写父类的 __init__ 方法
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['customer_province'].widget.choices = [("", "全国")] + get_states()
        self.fields['industry_1'].widget.choices = [("", "全部")] + get_industry_l1_list()
        self.fields['industry_2'].widget.choices = [("", "全部")] + get_industry_l2_list()

    def select_province(self,id):
        # 根据id设置省份
        self.initial["customer_province"] = id

    def select_industry1(self,id):
        # 根据行业id设置行业
        self.initial["industry_1"] = id

    def select_industry2(self,id):
        # 根据行业id设置行业
        self.initial["industry_2"] = id

    def input_competitorName(self,name):
        # 根据请求带的条件赋值
        self.initial['competitor_name'] = name


    def input_customerName(self, name):
        # 根据请求带的条件赋值
        self.initial['customer_name'] = name

competitor/views/getIP.py
from django.http import JsonResponse


def getIP(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')  # 判断是否使用代理
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0] # 使用代理获取真实的ip
    else:
        ip = request.META.get('REMOTE_ADDR') # 未使用代理获取IP

    # print(x_forwarded_for,ip)
    return JsonResponse({'ip':ip})

templates/competitor/competitor_analysis.html
{% extends 'base.html' %}
{% load i18n static %}

{% block css_tail %}
<!-- jqgrid-->
<link href="{% static 'css/plugins/jqgrid/ui.jqgrid.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
<link href="{% static 'css/competitor/css.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div style="display: none;">
        <div id="occupied_analysis">{% url 'competitor:occupied' %}</div>
        <div id="money_analysis">{% url 'competitor:money' %}</div>
        <div id="local_analysis">{% url 'competitor:local' %}</div>
        <div id="industry_analysis">{% url 'competitor:industry' %}</div>
        <div id="industry2_analysis">{% url 'competitor:industry2money' %}</div>
        <div id="status_analysis">{% url 'competitor:customerStatus' %}</div>
    </div>

    <a href={% url 'competitor:competitor_crm' %}?competitor_name={{ competitor_name }} target='_blank' ><h2 style="text-align: center;margin-top: 20px;margin-bottom: 20px;" id="competitor_id" value="{{ competitor_id }}">竞品名称：{{ competitor_name }}</h2> </a>
    <div class="evenAna_wrap">
        <div class="event_content">
            <div class="event a" the-id="baseinfo" module-id="1">
                <div class="event_text">
                    <p>竞品基本信息</p>
                </div>
                <div class="detail_text">
                    <p class="textarea" style="box-sizing: border-box;">{{ remark }}</p>
                </div>
            </div>
            <div class="event b" the-id="customer-status" module-id="2">
                <div class="event_text">
                    <p>签单客户状态
                        <i class="pictips" title="按照竞品签单客户与本公司的合作状态进行分析。"></i>
                    </p>
                </div>
                <div class="echart_wrap">
                    <ul class="introduce_total mg-20">
                        <li>
                            <p>总签单客户数</p>
                            <p>{{ total }}</p>
                        </li>
                        <li>
                            <p>合作中</p>
                            <p>{{ account1 }}</p>
                        </li>
                        <li>
                            <p>曾合作</p>
                            <p>{{ account2 }}</p>
                        </li>
                        <li>
                            <p>未合作</p>
                            <p>{{ account3 }}</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="event c" the-id="money" module-id="3">
                <div class="event_text">
                    <p>签单金额分布
                        <i class="pictips" title="按照竞品签单的金额进行分析。"></i>
                    </p>
                </div>
                <div class="echart_wrap">
                    <div class="ibox-content col-sm-12" style="margin-bottom: 20px;">
                        <div class="col-sm-9" id="moneyEcharts" style="width: 63%;height: 350px;"> </div>

                        <div class="jqGrid_wrapper col-sm-3" style="width: 35%;margin-left: 20px;">
                            <a href={% url 'competitor:competitor_crm' %}?competitor_name={{ competitor_name }} target='_blank' style="font-size:14px;">>>详情</a>
                            <table id="table_list_2" ></table>
                            <div id="pager_list_2" ></div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="event d" the-id="local" module-id="4">
                <div class="event_text">
                    <p>签单地域分布
                        <i class="pictips" title="按照竞品签单客户的地域分布进行分析。"></i>
                    </p>
                </div>
                <div class="echart_wrap">
                    <div class="ibox-content col-sm-12" style="margin:0 auto;margin-bottom: 20px;">
                        <div class="col-sm-9" id="localEcharts" style="margin:0 auto;width: 63%;height: 500px;"> </div>
                        <div class="jqGrid_wrapper col-sm-3" style="margin:0 auto;width: 35%;height: 500px;margin-left: 20px;">
                            <a href={% url 'competitor:competitor_crm' %}?competitor_name={{ competitor_name }} target='_blank' style="font-size:14px;">>>详情</a>
                            <table id="table_list_1" ></table>
                            <div id="pager_list_1" ></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="event e" the-id="industry1" module-id="5">
                <div class="event_text">
                    <p>签单行业分布
                        <i class="pictips" title="按照竞品签单客户的一级行业分布进行分析。"></i>
                    </p>
                </div>
                <div class="echart_wrap">
                    <div class="ibox-content" style="margin-bottom: 20px;">
                        <div id="industry1echarts" style="margin:0 auto;width: 500px;height: 400px;"> </div>
                    </div>
                </div>
            </div>
            <div class="event f" the-id="industry2" module-id="6">
                <div class="event_text">
                    <p>二级行业分析
                        <i class="pictips" title="按照竞品签单客户的二级行业及对应的签单平均金额和智慧星光签单对比进行分析。"></i>
                    </p>
                </div>
                <div class="echart_wrap">
                    <div class="ibox-content  col-sm-12" style="margin:0 auto;margin-bottom: 20px;">
                        <div class="col-sm-9" id="industry2echarts" style="margin:0 auto;width: 60%;height: 400px;"> </div>
                        <div class="jqGrid_wrapper col-sm-3" style="margin:0 auto;width: 38%;height: 400px;margin-left: 20px;">
                            <a href={% url 'competitor:competitor_crm' %}?competitor_name={{ competitor_name }} target='_blank' style="font-size:14px;">>>详情</a>
                            <table id="table_list_3" ></table>
                            <div id="pager_list_3" ></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="event g" the-id="customer" module-id="7">
                <div class="event_text">
                    <p>占有率分析
                        <i class="pictips" title="按照签单客户的数量进行分析。"></i>
                    </p>
                </div>
                <div class="echart_wrap">
                    <div class="ibox-content" style="margin-bottom: 20px;">
                        <div id="occupiedEcharts" style="margin:0 auto;width: 100%;height: 700px;"> </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="event_nav"></div>
    </div>


    <div id="init-data1" style="display: none;">{{ init_data1 }}</div>
    <div id="init-data2" style="display: none;">{{ init_data2 }}</div>
    <div id="init-data3" style="display: none;">{{ init_data3 }}</div>



{% endblock %}

{% block js_tail %}
    <!-- jqGrid -->
    <script src="{% static 'js/plugins/jqgrid/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'js/plugins/jqgrid/jquery.jqGrid.min.js' %}"></script>

    <script src="{% static 'js/plugins/echarts/echarts.js' %}"></script>
    <script src="{% static 'js/competitor/competitor_analysis.js' %}"></script>
    <script src="{% static 'js/plugins/echarts/china.js' %}"></script>
{% endblock %}